version: '3.9' 
services:
  db:
    platform: linux/amd64
    container_name: sample-db
    image: 'mysql:8.2.0'
    volumes: 
      - sample_db_data:/var/lib/mysql
    env_file:
      - ./app/env/db.env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 10s
  api:
    platform: linux/amd64
    container_name: sample-api
    build: .
    ports:
      - 5050:5050
    env_file:
      - ./app/env/api.env
    depends_on:
      db:
        condition: service_healthy
volumes:
  sample_db_data:
